name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "extensions/**"
  pull_request:
    paths:
      - "extensions/**"

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: macos-latest
    strategy:
      matrix:
        extension: [open-in-app]
    defaults:
      run:
        working-directory: extensions/${{ matrix.extension }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: extensions/${{ matrix.extension }}/package-lock.json
      - run: npm ci
      - run: npx ray build -e dist
      - run: npx eslint . --max-warnings 0 --ignore-pattern eslint.config.js
      - run: npx prettier --check "src/**" "*.json"
